### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [B1ackBoron/grid-template#1]
1)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.

![image](https://user-images.githubusercontent.com/8464662/236113764-90d43465-3e38-4ea1-aacd-ee274e79d124.png)

2)
внешний вид некорректен
![image](https://user-images.githubusercontent.com/8464662/236113919-411aa692-5d2d-4b85-9da7-d9d7904d04ce.png)
![image](https://user-images.githubusercontent.com/8464662/236113959-d8359f27-faa2-40b1-aa5d-68a3d5ea93db.png)

**Comment by B1ackBoron** [comment]
Добрый вечер, исправил

**Comment by Alecto** [comment]
2 посилання листом на почту будь ласка

чт, 4 трав. 2023, 21:51 користувач B1ackBoron ***@***.***>
пише:
